// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: aLuc5FJ4muSJEjCmsd2jqk
// Component: DehTHguGvHgpk
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: DBhKpuopLwsn-/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_saa_s_website.module.css"; // plasmic-import: aLuc5FJ4muSJEjCmsd2jqk/projectcss
import sty from "./PlasmicBlogPosts.module.css"; // plasmic-import: DehTHguGvHgpk/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: wzhID7krtZ3VKP/icon
import ArrowRightsvgIcon from "./icons/PlasmicIcon__ArrowRightsvg"; // plasmic-import: AAVZDp-i71oUAH/icon
import fakurianDesignPPTwRTkvXqUnsplashjpgIjkUnfHf6BpQq from "./images/fakurianDesignPPTwRTkvXqUnsplashjpg.jpeg"; // plasmic-import: IJKUnf_hf6bpQq/picture
import fakurianDesignLfbhDph3QYUnsplashjpgHwJnMhSg4GTAi from "./images/fakurianDesignLfbhDph3QYUnsplashjpg.jpeg"; // plasmic-import: HWJnMhSg4G-TAi/picture
import blog2390X290JpgXMe8ZZ1DHqapem from "./images/blog2390X290Jpg.jpeg"; // plasmic-import: XMe8zZ1dHqapem/picture

export type PlasmicBlogPosts__VariantMembers = {};
export type PlasmicBlogPosts__VariantsArgs = {};
type VariantPropType = keyof PlasmicBlogPosts__VariantsArgs;
export const PlasmicBlogPosts__VariantProps = new Array<VariantPropType>();

export type PlasmicBlogPosts__ArgsType = {};
type ArgPropType = keyof PlasmicBlogPosts__ArgsType;
export const PlasmicBlogPosts__ArgProps = new Array<ArgPropType>();

export type PlasmicBlogPosts__OverridesType = {
  root?: p.Flex<"section">;
  h2?: p.Flex<"h2">;
};

export interface DefaultBlogPostsProps {
  className?: string;
}

function PlasmicBlogPosts__RenderFunc(props: {
  variants: PlasmicBlogPosts__VariantsArgs;
  args: PlasmicBlogPosts__ArgsType;
  overrides: PlasmicBlogPosts__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <section
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.column__vd1Jn)}>
        <h2
          data-plasmic-name={"h2"}
          data-plasmic-override={overrides.h2}
          className={classNames(
            projectcss.all,
            projectcss.h2,
            projectcss.__wab_text,
            sty.h2
          )}
        >
          {"Blog"}
        </h2>

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__et234
          )}
        >
          {
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. \nLorem Ipsum has been the industry's standard dummy text ever since the 1500s"
          }
        </div>

        <div className={classNames(projectcss.all, sty.columns__a8E2M)}>
          <div className={classNames(projectcss.all, sty.column__uasDu)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__l57Gi)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: fakurianDesignPPTwRTkvXqUnsplashjpgIjkUnfHf6BpQq,
                fullWidth: 1920,
                fullHeight: 1280,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns___2Jzpi)}>
              <div className={classNames(projectcss.all, sty.column__qweNe)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xZnLl
                  )}
                >
                  {"January 03, 2021"}
                </div>

                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__wZrB
                  )}
                >
                  {"Convincing reasons you need to learn"}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dTueW
                  )}
                >
                  {
                    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ....\n"
                  }
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button__wKi7F)}
                  color={"softBlue" as const}
                  endIcon={
                    <ArrowRightsvgIcon
                      className={classNames(projectcss.all, sty.svg__uwS0M)}
                      role={"img"}
                    />
                  }
                  shape={"rounded" as const}
                  showEndIcon={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mjFph
                    )}
                  >
                    {"READ MORE"}
                  </div>
                </Button>
              </div>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.column__rQ7Az)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__o0611)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"100%" as const}
              loading={"lazy" as const}
              src={{
                src: fakurianDesignLfbhDph3QYUnsplashjpgHwJnMhSg4GTAi,
                fullWidth: 1920,
                fullHeight: 1080,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__d2J6G)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__vdrg)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__oH9Mb
                  )}
                >
                  {"January 03, 2021"}
                </div>

                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__zxNSr
                  )}
                >
                  {"The five devices you need to work anytime"}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bKdt0
                  )}
                >
                  {
                    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ....\n"
                  }
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button__oVxt0)}
                  color={"softBlue" as const}
                  endIcon={
                    <ArrowRightsvgIcon
                      className={classNames(projectcss.all, sty.svg__uqhI3)}
                      role={"img"}
                    />
                  }
                  shape={"rounded" as const}
                  showEndIcon={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mvaNb
                    )}
                  >
                    {"READ MORE"}
                  </div>
                </Button>
              </p.Stack>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.column__irJs5)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__ukK4)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"100%" as const}
              loading={"lazy" as const}
              src={{
                src: blog2390X290JpgXMe8ZZ1DHqapem,
                fullWidth: 390,
                fullHeight: 290,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__c6YQk)}>
              <div className={classNames(projectcss.all, sty.column___1LC85)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__d8Vh3
                  )}
                >
                  {"January 03, 2021"}
                </div>

                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__d1CLd
                  )}
                >
                  {"Tiktok Illegally collecting data sharing"}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zybeL
                  )}
                >
                  {
                    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ....\n"
                  }
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button___3C3EJ)}
                  color={"softBlue" as const}
                  endIcon={
                    <ArrowRightsvgIcon
                      className={classNames(projectcss.all, sty.svg___3F6R2)}
                      role={"img"}
                    />
                  }
                  shape={"rounded" as const}
                  showEndIcon={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___6Wu7L
                    )}
                  >
                    {"READ MORE"}
                  </div>
                </Button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "h2"],
  h2: ["h2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "section";
  h2: "h2";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBlogPosts__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBlogPosts__VariantsArgs;
    args?: PlasmicBlogPosts__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicBlogPosts__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicBlogPosts__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicBlogPosts__ArgProps,
          internalVariantPropNames: PlasmicBlogPosts__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicBlogPosts__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBlogPosts";
  } else {
    func.displayName = `PlasmicBlogPosts.${nodeName}`;
  }
  return func;
}

export const PlasmicBlogPosts = Object.assign(
  // Top-level PlasmicBlogPosts renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h2: makeNodeComponent("h2"),

    // Metadata about props expected for PlasmicBlogPosts
    internalVariantProps: PlasmicBlogPosts__VariantProps,
    internalArgProps: PlasmicBlogPosts__ArgProps
  }
);

export default PlasmicBlogPosts;
/* prettier-ignore-end */
